### PR TITLE
Refactor and add watchlist support

### PR DESCRIPTION
**Pull request by maccman**

### CODE REVIEW

**Comment by bendrucker** [comment]
@maccaw do you want me to look at this and merge?

**Comment by maccman** [comment]
If you can spare the time that would be amazing. We're planning on getting it out later today though.

**Comment by bendrucker** [comment]
Will do some quick cleanup and merge now. More significant simplifying can wait.

**Comment by bendrucker** [comment]
Squashed and merged

**Comment by bendrucker** [comment]
1.1.0 released

**Comment by maccman** [comment]
Awesome, thanks!

**Pull request closed without merging**
