### PR TITLE
Use arrow functions instead of .bind(this)

### PR DESCRIPTION
**Pull request by papandreou**
See #32

### CODE REVIEW

**Comment by papandreou** [comment]
Ah, I didn't notice that the module is being tested with node.js 0.10 on Travis until now :). I updated the branch to use a `var that = this` approach instead of arrow functions, in case 0.10 must still be supported :)

**Comment by papandreou** [comment]
Haven't observed #32 in our app after deploying this fix to production 3 days ago, so I think the fix is good :)

**Comment by holm** [comment]
Any chance to get a review of this?

**Comment by papandreou** [comment]
@davidlumley, ping?

**Comment by maccman** [comment]
Sorry, I don't think we will merge this. What's the issue with `bind`?

**Comment by davidlumley** [comment]
Sorry to hear NewRelic is breaking some things. I'm on vacation at the moment, but happy to discuss with @maccman when I get back.

**Comment by papandreou** [comment]
I've dug around some more and reported it to the newrelic folks, who have come up with a fix: https://github.com/newrelic/node-newrelic/pull/260#issuecomment-369089224

Thanks for taking the time to consider the issue, happy that it won't be necessary after all :)

**Pull request closed without merging**
